name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: setup
        run: npm ci

      - name: test
        run: npm run test:all

      - name: Code coverage report
        uses: codecov/codecov-action@v2
        with:
          yml: ./codecov.yml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittest
          name: codecov
